# Makefile

start-airflow:
    docker-compose -f docker-compose.yaml up -d

stop-airflow:
    docker-compose -f docker-compose.yaml down

restart-airflow:
    docker-compose -f docker-compose.yaml restart